[
  modules/automx.nix
  modules/base.nix
  modules/demockrazy.nix
  modules/docker-runner.nix
  modules/kvm.nix
  modules/machines.nix
  modules/mailman3.nix
  modules/monitoring/default.nix
  modules/openldap-ha.nix
  modules/router.nix
  modules/service-overview.nix
  modules/wireguard-tunnel.nix
]
